/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
//import modules

/**
 *
 * @author Chris
 */
public class NewJFrame extends javax.swing.JFrame {
    // Global app variables
    ArrayList<Account> accounts = new ArrayList<>();
    ArrayList<Question> questions = new ArrayList<>();
    
    CurrentUser curr_acc;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        objectifyUsers();
        objectifyQuestions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username_in = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password_in = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        signup_btn = new javax.swing.JButton();
        login_btn = new javax.swing.JButton();
        error_lab = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        ada = new javax.swing.JLabel();
        sda = new javax.swing.JLabel();
        signout_btn = new javax.swing.JButton();
        username_lab = new javax.swing.JLabel();
        qCorrect_lab = new javax.swing.JLabel();
        qWrong_lab = new javax.swing.JLabel();
        elo_lab = new javax.swing.JLabel();
        main_nav = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        welcome_dis = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        question_dis = new javax.swing.JTextPane();
        questionType_lab = new javax.swing.JLabel();
        nextQuestion_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        eloChange_lab = new javax.swing.JLabel();
        true_btn = new javax.swing.JButton();
        false_btn = new javax.swing.JButton();
        s1 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        s1_dis = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        s2_dis = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        s3_dis = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        s4_dis = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Spot the Fakie");

        username_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inActionPerformed(evt);
            }
        });

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        password_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_inActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("LOGIN/SIGNIN");

        signup_btn.setText("SIGNUP");
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });

        login_btn.setText("LOGIN");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(password_in)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(username_in))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(error_lab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(signup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(login_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup_btn)
                    .addComponent(login_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(error_lab)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setText("Current User");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Username:");

        l1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        l1.setText("Questions Correct:");

        ada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ada.setText("Questions Wrong:");

        sda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sda.setText("ELO:");

        signout_btn.setText("SIGNOUT");
        signout_btn.setEnabled(false);
        signout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signout_btnActionPerformed(evt);
            }
        });

        username_lab.setText("[NULL]");

        qCorrect_lab.setText("[NULL]");

        qWrong_lab.setText("[NULL]");

        elo_lab.setText("[NULL]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(username_lab))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(elo_lab))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qWrong_lab))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(l1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qCorrect_lab)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(username_lab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(qCorrect_lab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ada)
                    .addComponent(qWrong_lab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sda)
                    .addComponent(elo_lab))
                .addGap(18, 18, 18)
                .addComponent(signout_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_nav.setEnabled(false);

        welcome_dis.setEditable(false);
        welcome_dis.setText("Welcome to Spot the Fakie! This app will help you ");
        welcome_dis.setFocusable(false);
        jScrollPane2.setViewportView(welcome_dis);

        question_dis.setEditable(false);
        question_dis.setFocusable(false);
        jScrollPane5.setViewportView(question_dis);

        questionType_lab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        questionType_lab.setText("[QUESTION TYPE]");

        nextQuestion_btn.setText("Next Question");
        nextQuestion_btn.setEnabled(false);
        nextQuestion_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuestion_btnActionPerformed(evt);
            }
        });

        jLabel5.setText("ELO Change:");

        true_btn.setText("True");
        true_btn.setEnabled(false);
        true_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                true_btnActionPerformed(evt);
            }
        });

        false_btn.setText("False");
        false_btn.setEnabled(false);
        false_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                false_btnActionPerformed(evt);
            }
        });

        s1.setText("Select 1");
        s1.setToolTipText("");
        s1.setEnabled(false);
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        s2.setText("Select 2");
        s2.setEnabled(false);
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        s3.setText("Select 3");
        s3.setEnabled(false);
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        s4.setText("Select 4");
        s4.setEnabled(false);
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        s1_dis.setEditable(false);
        s1_dis.setFocusable(false);
        jScrollPane6.setViewportView(s1_dis);

        s2_dis.setEditable(false);
        s2_dis.setFocusable(false);
        jScrollPane7.setViewportView(s2_dis);

        s3_dis.setEditable(false);
        s3_dis.setFocusable(false);
        jScrollPane8.setViewportView(s3_dis);

        s4_dis.setEditable(false);
        s4_dis.setFocusable(false);
        jScrollPane9.setViewportView(s4_dis);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(s4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(s3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8))
                    .addComponent(questionType_lab)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(true_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eloChange_lab)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(false_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                                .addComponent(nextQuestion_btn))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s2)
                            .addComponent(s1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane7)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(questionType_lab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(eloChange_lab)
                                    .addComponent(nextQuestion_btn))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(true_btn)
                                    .addComponent(false_btn))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        main_nav.addTab("Question", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_nav))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(main_nav)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_inActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        Account account = findAccountByUsername(username_in.getText().trim());
        
        if (account != null) {
            if (account.getPassword().equals(password_in.getText())) {
                // Username and password are correct
                setOnbError("Logged in successful.");
                loginActions(account);
            } else {
                // Password is incorrect
                setOnbError("Incorrect password.");
            }
        } else {
            // Username not found
            setOnbError("User not found.");
        }
       
    }//GEN-LAST:event_login_btnActionPerformed

    
    
    private void signout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signout_btnActionPerformed
        // Clear input fields and unlock login and sign up
        username_in.setEditable(true);
        username_in.setEnabled(true);
        password_in.setText(null);
        password_in.setEditable(true);
        password_in.setEnabled(true);
        login_btn.setEnabled(true);
        signup_btn.setEnabled(true);
        
        // lock main app UI
        signout_btn.setEnabled(false);
        main_nav.setEnabled(false);  
        username_lab.setText(null);
        qCorrect_lab.setText(null);
        qWrong_lab.setText(null);
        elo_lab.setText(null);
        setOnbError("Logged out successfully.");
        
        // Main UI reset actions
        signoutActions();
        
    }//GEN-LAST:event_signout_btnActionPerformed

    private void username_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inActionPerformed

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        String username = username_in.getText().trim();
        String password = password_in.getText();
        
        if(username.isEmpty() || password.trim().isEmpty()) { //Checking for empty login fields
            setOnbError("Username and password cannot be empty.");
        } else {
            Account a = findAccountByUsername(username);
            // Finds account, if account doesn't exist in database adds account to database file
            if (a == null) {
                Account account = new Account(
                    username, password
                );

                accounts.add(account);
                account.addToDatabase();
                
                loginActions(account);
            } else {
                // Username already exists
                setOnbError("User already exists.");
            }
        }
        
        
    }//GEN-LAST:event_signup_btnActionPerformed

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        handleUserAnswer(1);
    }//GEN-LAST:event_s1ActionPerformed

    private void false_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_false_btnActionPerformed
        handleUserAnswer(false);
    }//GEN-LAST:event_false_btnActionPerformed

    private void true_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_true_btnActionPerformed
        handleUserAnswer(true);
    }//GEN-LAST:event_true_btnActionPerformed

    private void nextQuestion_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQuestion_btnActionPerformed
        // Display the new question by setting the question
        setQuestion();
    }//GEN-LAST:event_nextQuestion_btnActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        handleUserAnswer(2);
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        handleUserAnswer(3);
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        handleUserAnswer(4);
    }//GEN-LAST:event_s4ActionPerformed

    public void objectifyUsers() {
    // Reads user data from "usersData.txt" and question history from "questionsAnswered.txt"
    // creates Account object and adds them to the accounts list
        try {
            Scanner accountFile = new Scanner(new File("usersData.txt"));

            while (accountFile.hasNextLine()) {
                String line = accountFile.nextLine();
                String[] parts = line.split(";");

                if (parts.length == 5) {
                    String username = parts[0];
                    String password = parts[1];
                    int questionsCorrect = Integer.parseInt(parts[2]);
                    int questionsWrong = Integer.parseInt(parts[3]);
                    int elo = Integer.parseInt(parts[4]);

                    // Find matching questionsAnswered from file
                    String[] questionsAnswered = new String[0];
                    Scanner qaFile = new Scanner(new File("questionsAnswered.txt"));
                    while (qaFile.hasNextLine()) {
                        String qaLine = qaFile.nextLine();
                        String[] qaParts = qaLine.split(";");
                        if (qaParts.length == 2 && qaParts[0].equals(username)) {
                            questionsAnswered = qaParts[1].split(",");
                            break;
                        }
                    }
                    qaFile.close();

                    Account account = new Account(
                        username, password, questionsAnswered,
                        questionsCorrect, questionsWrong, elo
                    );

                    accounts.add(account);
                } else {
                    System.out.println("Invalid account line: " + line);
                }
            }

            accountFile.close();

        } catch (FileNotFoundException e) {
            System.out.println("File not found: " + e.getMessage());
        }
    }
    
    public void objectifyQuestions() {
        int tfCounter = 1;
        int mcCounter = 1;

        try {
            // Read true/false questions
            Scanner tfFile = new Scanner(new File("truefalse.txt"));
            while (tfFile.hasNextLine()) {
                String line = tfFile.nextLine();
                String[] parts = line.split(";");
                if (parts.length == 3) {
                    String question = parts[0];
                    String tip = parts[2];
                    boolean answer = Boolean.parseBoolean(parts[1]);
                    String id = "TF" + tfCounter++;

                    Question q = new TrueFalse(question, tip, id, answer);
                    questions.add(q);
                } else {
                    System.out.println("Invalid true/false line: " + line);
                }
            }
            tfFile.close();

            // Read multiple choice questions
            Scanner mcFile = new Scanner(new File("multiplechoice.txt"));
            while (mcFile.hasNextLine()) {
                String line = mcFile.nextLine();
                String[] parts = line.split(";");
                if (parts.length == 7) {
                    String question = parts[0];
                    String tip = parts[2];
                    int answer = Integer.parseInt(parts[1]); // index 0-3
                    String[] choices = {parts[3], parts[4], parts[5], parts[6]};
                    String id = "MC" + mcCounter++;

                    Question q = new MultipleChoice(question, tip, id, answer, choices);
                    questions.add(q);
                } else {
                    System.out.println("Invalid multiple choice line: " + line);
                }
            }
            mcFile.close();

        } catch (FileNotFoundException e) {
            System.out.println("Question file not found: " + e.getMessage());
        }
    }
    
    public Account findAccountByUsername(String username) {
        for (Account account : accounts) {
            if (account.getUsername().equals(username)) {
                return account;
            }
        }
        return null;
    }
    
    public void clearOnbError() {
        error_lab.setText(null);
    }   
    
    public void setOnbError(String error) {
        error_lab.setText(error);
    }  
    
    public void loginActions(Account account) {
        // Set the current account
        curr_acc = new CurrentUser(
                account.getUsername(),
                account.getPassword(),
                account.getQuestionsAnswered(),
                account.getQuestionsCorrect(),
                account.getQuestionsWrong(),
                account.getELO()
        );
        
        // Clear input fields and lock login and sign up
        username_in.setText(null);
        username_in.setEditable(false);
        username_in.setEnabled(false);
        password_in.setText(null);
        password_in.setEditable(false);
        password_in.setEnabled(false);
        login_btn.setEnabled(false);
        signup_btn.setEnabled(false);
        
        // Unlock main app UI
        signout_btn.setEnabled(true);
        main_nav.setEnabled(true);
        
        // Set current user stats
        username_lab.setText(curr_acc.getUsername());
        qCorrect_lab.setText(Integer.toString(curr_acc.getQuestionsCorrect()));
        qWrong_lab.setText(Integer.toString(curr_acc.getQuestionsWrong()));
        elo_lab.setText(Integer.toString(curr_acc.getELO()));
        
        // Generate a question
        curr_acc.genQuestion(questions);
        
        // Display and set up question
        setQuestion();
        

    }
    
    public void signoutActions() {
        // Toggle all false
        toggleMC_s(false);
        toggleTF_s(false);
        nextQuestion_btn.setEnabled(false);
        
        
        // Reset MC selections and question 
        s1_dis.setText(null);
        s2_dis.setText(null);
        s3_dis.setText(null);
        s4_dis.setText(null);
        question_dis.setText(null);
        eloChange_lab.setText(null);
        questionType_lab.setText("[QUESTION TYPE]");
    }
    
    public void setQuestion() {
        Question current_q = curr_acc.getQuestion();
        
        // Set the question type
        if(current_q instanceof TrueFalse) {
            questionType_lab.setText("True or False?");
            
            // Open selection for true false
            toggleTF_s(true);
        } else if(current_q instanceof MultipleChoice) {
            String[] choices = ((MultipleChoice) current_q).getChoices();
            questionType_lab.setText("Multiple Choice");
            
            // Open selection for multiple choice
            toggleMC_s(true);
            
            // Set the selections
            s1_dis.setText(choices[0]);
            s2_dis.setText(choices[1]);
            s3_dis.setText(choices[2]);
            s4_dis.setText(choices[3]);
        }
        
        // Set question text
        question_dis.setText(current_q.getQuestion());
    }
    
    public void toggleMC_s(boolean state) {
        s1.setEnabled(state);
        s2.setEnabled(state);
        s3.setEnabled(state);
        s4.setEnabled(state);
        
        if(state == false) {
            // Empty all the displays for selection
            s1_dis.setText(null);
            s2_dis.setText(null);
            s3_dis.setText(null);
            s4_dis.setText(null);
        }
    }
    
    public void toggleTF_s(boolean state) {
        true_btn.setEnabled(state);
        false_btn.setEnabled(state);
    }
    
    public void handleUserAnswer(boolean answer) {
        // Lock selections 
        toggleTF_s(false);
        
        // Unlock next question button
        nextQuestion_btn.setEnabled(true);
        
        TrueFalse current_q = (TrueFalse) curr_acc.getQuestion();
        boolean isCorrect = current_q.checkAnswer(answer);
        
        if(isCorrect) {
            // Display correct with tips
            question_dis.setText("You are correct! The answer was "+ answer + ".\n\n TIP: " + current_q.getTip());
            
            // Add elo to user
            curr_acc.addElo(curr_acc.getQuestion().getEloGain());
            
            // Display elo change
            eloChange_lab.setText("+" + curr_acc.getQuestion().getEloGain());
            
            // Increase correct questions
            curr_acc.addQuestionsCorrect();
        } else {
             // Display incorrect with tips
            question_dis.setText("You are incorrect! The answer was "+ answer + ".\n\n TIP: " + current_q.getTip());
            
             // Remove elo from user
            curr_acc.removeElo(curr_acc.getQuestion().getEloLose());
            
            // Display elo change
            eloChange_lab.setText("-" + curr_acc.getQuestion().getEloLose());
            
            // Increase incorrect questions
            curr_acc.addQuestionsWrong();
        }
        
        updateCurrentUser();
        
    }
    
    public void handleUserAnswer(int answer) {
        // Lock selections 
        toggleMC_s(false);
        
        // Unlock next question button
        nextQuestion_btn.setEnabled(true);
        
        MultipleChoice current_q = (MultipleChoice) curr_acc.getQuestion();
        boolean isCorrect = current_q.checkAnswer(answer);
        
        if(isCorrect) {
            // Display correct with tips
            question_dis.setText("You are correct! The answer was "+ answer + ".\n\n TIP: " + current_q.getTip());
            
            // Add elo to user
            curr_acc.addElo(curr_acc.getQuestion().getEloGain());
            
            // Display elo change
            eloChange_lab.setText("+" + curr_acc.getQuestion().getEloGain());
            
            // Increase correct questions
            curr_acc.addQuestionsCorrect();
        } else {
             // Display incorrect with tips
            question_dis.setText("You are incorrect! The answer was "+ answer + ".\n\n TIP: " + current_q.getTip());
            
             // Remove elo from user
            curr_acc.removeElo(curr_acc.getQuestion().getEloLose());
            
            // Display elo change
            eloChange_lab.setText("-" + curr_acc.getQuestion().getEloLose());
            
            // Increase incorrect questions
            curr_acc.addQuestionsWrong();
        }
        
        updateCurrentUser();
    }
    
    public void updateCurrentUser() {
         // Set current user stats
        username_lab.setText(curr_acc.getUsername());
        qCorrect_lab.setText(Integer.toString(curr_acc.getQuestionsCorrect()));
        qWrong_lab.setText(Integer.toString(curr_acc.getQuestionsWrong()));
        elo_lab.setText(Integer.toString(curr_acc.getELO()));
        
        // Generate a new question
        curr_acc.genQuestion(questions);
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ada;
    private javax.swing.JLabel eloChange_lab;
    private javax.swing.JLabel elo_lab;
    private javax.swing.JLabel error_lab;
    private javax.swing.JButton false_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel l1;
    private javax.swing.JButton login_btn;
    private javax.swing.JTabbedPane main_nav;
    private javax.swing.JButton nextQuestion_btn;
    private javax.swing.JTextField password_in;
    private javax.swing.JLabel qCorrect_lab;
    private javax.swing.JLabel qWrong_lab;
    private javax.swing.JLabel questionType_lab;
    private javax.swing.JTextPane question_dis;
    private javax.swing.JButton s1;
    private javax.swing.JTextPane s1_dis;
    private javax.swing.JButton s2;
    private javax.swing.JTextPane s2_dis;
    private javax.swing.JButton s3;
    private javax.swing.JTextPane s3_dis;
    private javax.swing.JButton s4;
    private javax.swing.JTextPane s4_dis;
    private javax.swing.JLabel sda;
    private javax.swing.JButton signout_btn;
    private javax.swing.JButton signup_btn;
    private javax.swing.JButton true_btn;
    private javax.swing.JTextField username_in;
    private javax.swing.JLabel username_lab;
    private javax.swing.JTextPane welcome_dis;
    // End of variables declaration//GEN-END:variables
}
